In [6]:
#use spread

In [7]:
import pandas as pd
import numpy as np



pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

In [8]:
df = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_betting_spread.csv')
df.head()

,game_id,book_name,book_id,team_id,a_team_id,spread1,spread2,price1,price2
0,21000358,Pinnacle Sports,238,1610612749,1610612742,7.5,-7.5,-106.0,-104.0
1,21000358,5Dimes,19,1610612749,1610612742,7.5,-7.5,-110.0,-110.0
2,21000358,Bookmaker,93,1610612749,1610612742,7.5,-7.5,-110.0,-110.0
3,21000358,BetOnline,1096,1610612749,1610612742,7.5,-7.5,-110.0,-110.0
4,21000358,Bovada,999996,1610612749,1610612742,8.0,-8.0,-115.0,-105.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131690 entries, 0 to 131689
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   game_id    131690 non-null  int64
 1   book_name  131690 non-null  object
 2   book_id    131690 non-null  int64
 3   team_id    131690 non-null  int64
 4   a_team_id  131690 non-null  int64
 5   spread1    131690 non-null  float64
 6   spread2    131690 non-null  float64
 7   price1     131690 non-null  float64
 8   price2     131690 non-null  float64
dtypes: float64(4), int64(4), object(1)
memory usage: 9.0+ MB

In [10]:
def american_odds_to_implied_prob(df_, col_):
    ml_neg = df_[df_[col_] < 0][col_]
    favorite = (-1 * ml_neg) / (100 + (-1) * ml_neg)
    
    ml_pos = df_[df_[col_] > 0][col_]
    underdog = 100 / (ml_pos + 100)
    
    df_ = pd.concat([favorite, underdog], axis=0)
    return df_.sort_index()

In [11]:
df['price1_implied_prob'] = american_odds_to_implied_prob(df, 'price1')
df['price2_implied_prob'] = american_odds_to_implied_prob(df, 'price2')

In [12]:
df.head(111)

,game_id,book_name,book_id,team_id,a_team_id,spread1,spread2,price1,price2,price1_implied_prob,price2_implied_prob
0,21000358,Pinnacle Sports,238,1610612749,1610612742,7.5,-7.5,-106.0,-104.0,0.514563,0.509804
1,21000358,5Dimes,19,1610612749,1610612742,7.5,-7.5,-110.0,-110.0,0.523810,0.523810
2,21000358,Bookmaker,93,1610612749,1610612742,7.5,-7.5,-110.0,-110.0,0.523810,0.523810
3,21000358,BetOnline,1096,1610612749,1610612742,7.5,-7.5,-110.0,-110.0,0.523810,0.523810
4,21000358,Bovada,999996,1610612749,1610612742,8.0,-8.0,-115.0,-105.0,0.534884,0.512195
5,21000358,Intertops,180,1610612749,1610612742,7.5,-7.5,-109.0,-109.0,0.521531,0.521531
6,21000358,YouWager,139,1610612749,1610612742,7.5,-7.5,-110.0,-110.0,0.523810,0.523810
7,21000358,JustBet,1275,1610612749,1610612742,7.5,-7.5,-110.0,-110.0,0.523810,0.523810
8,21000358,Sportsbetting,999991,1610612749,1610612742,7.5,-7.5,-110.0,-110.0,0.523810,0.523810
9,21000361,Pinnacle Sports,238,1610612755,1610612751,-1.5,1.5,-102.0,-108.0,0.504950,0.519231
10,21000361,5Dimes,19,1610612755,1610612751,-1.5,1.5,-105.0,-105.0,0.512195,0.512195
11,21000361,Bookmaker,93,1610612755,1610612751,-1.5,1.5,-110.0,-110.0,0.523810,0.523810
12,21000361,BetOnline,1096,1610612755,1610612751,-1.5,1.5,-110.0,-110.0,0.523810,0.523810
13,21000361,Bovada,999996,1610612755,1610612751,-2.0,2.0,-115.0,-105.0,0.534884,0.512195
14,21000361,Intertops,180,1610612755,1610612751,-1.5,1.5,-109.0,-109.0,0.521531,0.521531
15,21000361,YouWager,139,1610612755,1610612751,-1.5,1.5,-110.0,-110.0,0.523810,0.523810
16,21000361,JustBet,1275,1610612755,1610612751,-1.5,1.5,-110.0,-110.0,0.523810,0.523810
17,21000361,Sportsbetting,999991,1610612755,1610612751,-1.5,1.5,-110.0,-110.0,0.523810,0.523810
18,21000362,Pinnacle Sports,238,1610612747,1610612764,-10.5,10.5,102.0,-112.0,0.495050,0.528302
19,21000362,5Dimes,19,1610612747,1610612764,-10.0,10.0,-106.0,-104.0,0.514563,0.509804
20,21000362,Bookmaker,93,1610612747,1610612764,-10.5,10.5,-110.0,-110.0,0.523810,0.523810
21,21000362,BetOnline,1096,1610612747,1610612764,-10.5,10.5,-110.0,-110.0,0.523810,0.523810
22,21000362,Bovada,999996,1610612747,1610612764,-11.0,11.0,-110.0,-110.0,0.523810,0.523810
23,21000362,Intertops,180,1610612747,1610612764,-10.5,10.5,-104.0,-114.0,0.509804,0.532710
24,21000362,YouWager,139,1610612747,1610612764,-10.5,10.5,-110.0,-110.0,0.523810,0.523810
25,21000362,JustBet,1275,1610612747,1610612764,-10.5,10.5,-110.0,-110.0,0.523810,0.523810
26,21000362,Sportsbetting,999991,1610612747,1610612764,-10.5,10.5,-110.0,-110.0,0.523810,0.523810
27,21000367,Pinnacle Sports,238,1610612747,1610612754,-3.5,3.5,-110.0,100.0,0.523810,0.500000
28,21000367,5Dimes,19,1610612747,1610612754,-3.5,3.5,-107.0,-103.0,0.516908,0.507389
29,21000367,Bookmaker,93,1610612747,1610612754,-3.5,3.5,-110.0,-110.0,0.523810,0.523810
30,21000367,BetOnline,1096,1610612747,1610612754,-3.5,3.5,-110.0,-110.0,0.523810,0.523810
31,21000367,Bovada,999996,1610612747,1610612754,-4.5,4.5,-105.0,-115.0,0.512195,0.534884
32,21000367,Intertops,180,1610612747,1610612754,-3.5,3.5,-109.0,-109.0,0.521531,0.521531
33,21000367,YouWager,139,1610612747,1610612754,-4.0,4.0,-110.0,-110.0,0.523810,0.523810
34,21000367,JustBet,1275,1610612747,1610612754,-4.0,4.0,-110.0,-110.0,0.523810,0.523810
35,21000367,Sportsbetting,999991,1610612747,1610612754,-3.5,3.5,-110.0,-110.0,0.523810,0.523810
36,21000372,Pinnacle Sports,238,1610612766,1610612763,8.5,-8.5,-108.0,-102.0,0.519231,0.504950
37,21000372,5Dimes,19,1610612766,1610612763,8.5,-8.5,-107.0,-103.0,0.516908,0.507389
38,21000372,Bookmaker,93,1610612766,1610612763,8.5,-8.5,-110.0,-110.0,0.523810,0.523810
39,21000372,BetOnline,1096,1610612766,1610612763,8.5,-8.5,-110.0,-110.0,0.523810,0.523810
40,21000372,Bovada,999996,1610612766,1610612763,8.5,-8.5,-110.0,-110.0,0.523810,0.523810
41,21000372,Intertops,180,1610612766,1610612763,8.5,-8.5,-114.0,-104.0,0.532710,0.509804
42,21000372,YouWager,139,1610612766,1610612763,9.0,-9.0,-110.0,-110.0,0.523810,0.523810
43,21000372,JustBet,1275,1610612766,1610612763,8.5,-8.5,-110.0,-110.0,0.523810,0.523810
44,21000372,Sportsbetting,999991,1610612766,1610612763,8.5,-8.5,-110.0,-110.0,0.523810,0.523810
45,21000376,Pinnacle Sports,238,1610612750,1610612756,9.5,-9.5,100.0,-110.0,0.500000,0.523810
46,21000376,5Dimes,19,1610612750,1610612756,10.0,-10.0,-105.0,-105.0,0.512195,0.512195
47,21000376,Bookmaker,93,1610612750,1610612756,10.0,-10.0,-110.0,-110.0,0.523810,0.523810
48,21000376,BetOnline,1096,1610612750,1610612756,10.0,-10.0,-110.0,-110.0,0.523810,0.523810
49,21000376,Bovada,999996,1610612750,1610612756,10.0,-10.0,-110.0,-110.0,0.523810,0.523810
50,21000376,Intertops,180,1610612750,1610612756,9.5,-9.5,-104.0,-114.0,0.509804,0.532710
51,21000376,YouWager,139,1610612750,1610612756,10.0,-10.0,-110.0,-110.0,0.523810,0.523810
52,21000376,JustBet,1275,1610612750,1610612756,10.0,-10.0,-110.0,-110.0,0.523810,0.523810
53,21000376,Sportsbetting,999991,1610612750,1610612756,10.0,-10.0,-110.0,-110.0,0.523810,0.523810
54,21000378,Pinnacle Sports,238,1610612764,1610612751,6.5,-6.5,-116.0,105.0,0.537037,0.487805
55,21000378,5Dimes,19,1610612764,1610612751,6.0,-6.0,-102.0,-108.0,0.504950,0.519231
56,21000378,Bookmaker,93,1610612764,1610612751,6.5,-6.5,-110.0,-110.0,0.523810,0.523810
57,21000378,BetOnline,1096,1610612764,1610612751,6.0,-6.0,-110.0,-110.0,0.523810,0.523810
58,21000378,Bovada,999996,1610612764,1610612751,6.5,-6.5,-105.0,-115.0,0.512195,0.534884
59,21000378,Intertops,180,1610612764,1610612751,6.5,-6.5,-109.0,-109.0,0.521531,0.521531
60,21000378,YouWager,139,1610612764,1610612751,6.5,-6.5,-110.0,-110.0,0.523810,0.523810
61,21000378,JustBet,1275,1610612764,1610612751,6.5,-6.5,-110.0,-110.0,0.523810,0.523810
62,21000378,Sportsbetting,999991,1610612764,1610612751,6.0,-6.0,-110.0,-110.0,0.523810,0.523810
63,21000384,Pinnacle Sports,238,1610612751,1610612761,5.5,-5.5,-106.0,-104.0,0.514563,0.509804
64,21000384,5Dimes,19,1610612751,1610612761,5.5,-5.5,-105.0,-105.0,0.512195,0.512195
65,21000384,Bookmaker,93,1610612751,1610612761,5.5,-5.5,-110.0,-110.0,0.523810,0.523810
66,21000384,BetOnline,1096,1610612751,1610612761,5.5,-5.5,-110.0,-110.0,0.523810,0.523810
67,21000384,Bovada,999996,1610612751,1610612761,6.0,-6.0,-115.0,-105.0,0.534884,0.512195
68,21000384,Intertops,180,1610612751,1610612761,5.5,-5.5,-109.0,-109.0,0.521531,0.521531
69,21000384,YouWager,139,1610612751,1610612761,5.5,-5.5,-110.0,-110.0,0.523810,0.523810
70,21000384,JustBet,1275,1610612751,1610612761,5.5,-5.5,-110.0,-110.0,0.523810,0.523810
71,21000384,Sportsbetting,999991,1610612751,1610612761,5.5,-5.5,-110.0,-110.0,0.523810,0.523810
72,21000382,Pinnacle Sports,238,1610612748,1610612752,-5.0,5.0,-101.0,-109.0,0.502488,0.521531
73,21000382,5Dimes,19,1610612748,1610612752,-5.0,5.0,-101.0,-109.0,0.502488,0.521531
74,21000382,Bookmaker,93,1610612748,1610612752,-5.0,5.0,-110.0,-110.0,0.523810,0.523810
75,21000382,BetOnline,1096,1610612748,1610612752,-5.0,5.0,-110.0,-110.0,0.523810,0.523810
76,21000382,Bovada,999996,1610612748,1610612752,-5.5,5.5,-110.0,-110.0,0.523810,0.523810
77,21000382,Intertops,180,1610612748,1610612752,-5.0,5.0,-109.0,-109.0,0.521531,0.521531
78,21000382,YouWager,139,1610612748,1610612752,-5.0,5.0,-110.0,-110.0,0.523810,0.523810
79,21000382,JustBet,1275,1610612748,1610612752,-5.0,5.0,-110.0,-110.0,0.523810,0.523810
80,21000382,Sportsbetting,999991,1610612748,1610612752,-5.0,5.0,-110.0,-110.0,0.523810,0.523810
81,21000385,Pinnacle Sports,238,1610612766,1610612737,6.5,-6.5,102.0,-113.0,0.495050,0.530516
82,21000385,5Dimes,19,1610612766,1610612737,7.0,-7.0,-108.0,-102.0,0.519231,0.504950
83,21000385,Bookmaker,93,1610612766,1610612737,7.0,-7.0,-110.0,-110.0,0.523810,0.523810
84,21000385,BetOnline,1096,1610612766,1610612737,7.0,-7.0,-110.0,-110.0,0.523810,0.523810
85,21000385,Bovada,999996,1610612766,1610612737,7.0,-7.0,-110.0,-110.0,0.523810,0.523810
86,21000385,Intertops,180,1610612766,1610612737,6.5,-6.5,-109.0,-109.0,0.521531,0.521531
87,21000385,YouWager,139,1610612766,1610612737,7.0,-7.0,-110.0,-110.0,0.523810,0.523810
88,21000385,JustBet,1275,1610612766,1610612737,7.0,-7.0,-110.0,-110.0,0.523810,0.523810
89,21000385,Sportsbetting,999991,1610612766,1610612737,7.0,-7.0,-110.0,-110.0,0.523810,0.523810
90,21000419,Pinnacle Sports,238,1610612744,1610612758,3.0,-3.0,-109.0,-101.0,0.521531,0.502488
91,21000419,5Dimes,19,1610612744,1610612758,3.0,-3.0,-105.0,-105.0,0.512195,0.512195
92,21000419,Bookmaker,93,1610612744,1610612758,3.0,-3.0,-110.0,-110.0,0.523810,0.523810
93,21000419,BetOnline,1096,1610612744,1610612758,3.0,-3.0,-110.0,-110.0,0.523810,0.523810
94,21000419,Bovada,999996,1610612744,1610612758,3.0,-3.0,-110.0,-110.0,0.523810,0.523810
95,21000419,Intertops,180,1610612744,1610612758,3.0,-3.0,-109.0,-109.0,0.521531,0.521531
96,21000419,YouWager,139,1610612744,1610612758,3.0,-3.0,-110.0,-110.0,0.523810,0.523810
97,21000419,JustBet,1275,1610612744,1610612758,3.0,-3.0,-110.0,-110.0,0.523810,0.523810
98,21000419,Sportsbetting,999991,1610612744,1610612758,3.0,-3.0,-110.0,-110.0,0.523810,0.523810
99,21000421,Pinnacle Sports,238,1610612739,1610612737,9.5,-9.5,-106.0,-104.0,0.514563,0.509804
100,21000421,5Dimes,19,1610612739,1610612737,9.5,-9.5,-105.0,-105.0,0.512195,0.512195
101,21000421,Bookmaker,93,1610612739,1610612737,9.5,-9.5,-110.0,-110.0,0.523810,0.523810
102,21000421,BetOnline,1096,1610612739,1610612737,9.5,-9.5,-110.0,-110.0,0.523810,0.523810
103,21000421,Bovada,999996,1610612739,1610612737,9.5,-9.5,-110.0,-110.0,0.523810,0.523810
104,21000421,Intertops,180,1610612739,1610612737,9.5,-9.5,-109.0,-109.0,0.521531,0.521531
105,21000421,YouWager,139,1610612739,1610612737,9.5,-9.5,-110.0,-110.0,0.523810,0.523810
106,21000421,JustBet,1275,1610612739,1610612737,9.5,-9.5,-110.0,-110.0,0.523810,0.523810
107,21000421,Sportsbetting,999991,1610612739,1610612737,9.5,-9.5,-110.0,-110.0,0.523810,0.523810
108,21000422,Pinnacle Sports,238,1610612765,1610612761,5.0,-5.0,-101.0,-109.0,0.502488,0.521531
109,21000422,5Dimes,19,1610612765,1610612761,5.0,-5.0,-102.0,-108.0,0.504950,0.519231
110,21000422,Bookmaker,93,1610612765,1610612761,5.0,-5.0,-110.0,-110.0,0.523810,0.523810

<font color='red'> there some sort of trading fee associated?????</font>

<font color='red'>why am i seeing implied probability above .5 on both sides???????</font>

In [ ]:
#actual score for each of these games was?????

In [20]:
df['game_id'].unique()

array([21000358, 21000361, 21000362, ..., 21501150, 21501151, 21501152],
      dtype=int64)

In [21]:
len(df['game_id'].unique())

14914

In [ ]:
#game score for each of the game_id's

In [22]:
df2 = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_games_all.csv')
df2.head()

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
0,20800741,2009-02-06,SAC vs. UTA,1610612762,f,W,29.0,22.0,0.569,240,39.0,74.0,0.527,4.0,13.0,0.308,29.0,37.0,1.0,8.0,36.0,44,19.0,5.0,4.0,18.0,26.0,111,1610612758,2008,Regular Season,2008-09
1,20800701,2009-01-31,POR vs. UTA,1610612762,f,L,26.0,22.0,0.542,240,37.0,68.0,0.544,5.0,20.0,0.250,29.0,37.0,1.0,7.0,20.0,27,17.0,6.0,0.0,15.0,22.0,108,1610612757,2008,Regular Season,2008-09
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
3,20800558,2009-01-12,IND @ UTA,1610612762,t,W,23.0,15.0,0.605,240,39.0,85.0,0.459,8.0,18.0,0.444,34.0,37.0,1.0,9.0,31.0,40,24.0,10.0,6.0,8.0,20.0,120,1610612754,2008,Regular Season,2008-09
4,20800440,2008-12-27,HOU vs. UTA,1610612762,f,L,18.0,14.0,0.563,290,49.0,100.0,0.490,5.0,13.0,0.385,12.0,18.0,1.0,11.0,29.0,40,35.0,13.0,7.0,9.0,27.0,115,1610612745,2008,Regular Season,2008-09

<font color='red'> is_home f is false, t is true????? checking for index 2 and 3 as false and true</font>
    
appears to check out, https://www.basketball-reference.com/boxscores/200901160MEM.html, https://www.basketball-reference.com/boxscores/200901120UTA.html

In [23]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125624 entries, 0 to 125623
Data columns (total 32 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   game_id      125624 non-null  int64
 1   game_date    119376 non-null  object
 2   matchup      125624 non-null  object
 3   team_id      125624 non-null  int64
 4   is_home      125624 non-null  object
 5   wl           125614 non-null  object
 6   w            41000 non-null   float64
 7   l            41000 non-null   float64
 8   w_pct        41000 non-null   float64
 9   min          125624 non-null  int64
 10  fgm          125607 non-null  float64
 11  fga          90894 non-null   float64
 12  fg_pct       90871 non-null   float64
 13  fg3m         95248 non-null   float64
 14  fg3a         84316 non-null   float64
 15  fg3_pct      80062 non-null   float64
 16  ftm          125605 non-null  float64
 17  fta          120011 non-null  float64
 18  ft_pct       119960 non-null  float64
 19  oreb         83786 non-null   float64
 20  dreb         83639 non-null   float64
 21  reb          125624 non-null  int64
 22  ast          90068 non-null   float64
 23  stl          83960 non-null   float64
 24  blk          84407 non-null   float64
 25  tov          84293 non-null   float64
 26  pf           121742 non-null  float64
 27  pts          125624 non-null  int64
 28  a_team_id    125624 non-null  int64
 29  season_year  125624 non-null  int64
 30  season_type  125624 non-null  object
 31  season       125624 non-null  object
dtypes: float64(19), int64(7), object(6)
memory usage: 30.7+ MB

In [28]:
df2[df2['game_id'] == 20800584]

,game_id,game_date,matchup,team_id,is_home,wl,w,l,w_pct,min,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,stl,blk,tov,pf,pts,a_team_id,season_year,season_type,season
2,20800584,2009-01-16,MEM vs. UTA,1610612762,f,W,24.0,16.0,0.600,240,37.0,71.0,0.521,7.0,19.0,0.368,20.0,27.0,1.0,7.0,26.0,33,23.0,9.0,3.0,15.0,22.0,101,1610612763,2008,Regular Season,2008-09
27,20800584,2009-01-16,UTA @ MEM,1610612763,t,L,11.0,28.0,0.282,240,32.0,75.0,0.427,3.0,12.0,0.250,24.0,29.0,1.0,13.0,22.0,35,15.0,8.0,6.0,16.0,24.0,91,1610612762,2008,Regular Season,2008-09

In [29]:
df2[df2['game_id'] == 20800584][['game_id','matchup','team_id','pts']]

     game_id      matchup     team_id  pts
2   20800584  MEM vs. UTA  1610612762  101
27  20800584    UTA @ MEM  1610612763   91

In [31]:
#check team_id team name table just for another check????

df3 = pd.read_csv('C:\\Users\\Paul\\sb\\Untitled Folder\\raw_data\\nba_teams_all.csv')
df3.head(111)

    league_id     team_id  min_year  max_year abbreviation
0           0  1610612737    1949.0    2018.0          ATL
1           0  1610612738    1946.0    2018.0          BOS
2           0  1610612739    1970.0    2018.0          CLE
3           0  1610612740    2002.0    2018.0          NOP
4           0  1610612741    1966.0    2018.0          CHI
5           0  1610612742    1980.0    2018.0          DAL
6           0  1610612743    1976.0    2018.0          DEN
7           0  1610612744    1946.0    2018.0          GSW
8           0  1610612745    1967.0    2018.0          HOU
9           0  1610612746    1970.0    2018.0          LAC
10          0  1610612747    1948.0    2018.0          LAL
11          0  1610612748    1988.0    2018.0          MIA
12          0  1610612749    1968.0    2018.0          MIL
13          0  1610612750    1989.0    2018.0          MIN
14          0  1610612751    1976.0    2018.0          BKN
15          0  1610612752    1946.0    2018.0          NYK
16          0  1610612753    1989.0    2018.0          ORL
17          0  1610616834       NaN       NaN          NaN
18          0  1610616833       NaN       NaN          NaN
19          0       12306       NaN       NaN          NaN
20          0       12303       NaN       NaN          NaN
21          0       12313       NaN       NaN          NaN
22          0       12316       NaN       NaN          NaN
23          0          45       NaN       NaN          NaN
24          0       12308       NaN       NaN          NaN
25          0       12304       NaN       NaN          NaN
26          0       12320       NaN       NaN          NaN
27          0       12315       NaN       NaN          NaN
28          0          94       NaN       NaN          NaN
29          0       12321       NaN       NaN          NaN
30          0       12324       NaN       NaN          NaN
31          0          93       NaN       NaN          NaN
32          0          41       NaN       NaN          NaN
33          0       12325       NaN       NaN          NaN
34          0       12323       NaN       NaN          NaN
35          0       12330       NaN       NaN          NaN
36          0       15015       NaN       NaN          NaN
37          0       15018       NaN       NaN          NaN
38          0       12329       NaN       NaN          NaN
39          0       15016       NaN       NaN          NaN
40          0       15017       NaN       NaN          NaN
41          0  1610612754    1976.0    2018.0          IND
42          0  1610612755    1949.0    2018.0          PHI
43          0  1610612756    1968.0    2018.0          PHX
44          0  1610612757    1970.0    2018.0          POR
45          0  1610612758    1948.0    2018.0          SAC
46          0  1610612759    1976.0    2018.0          SAS
47          0  1610612760    1967.0    2018.0          OKC
48          0  1610612761    1995.0    2018.0          TOR
49          0  1610612762    1974.0    2018.0          UTA
50          0  1610612763    1995.0    2018.0          MEM
51          0  1610612764    1961.0    2018.0          WAS
52          0  1610612765    1948.0    2018.0          DET
53          0  1610612766    1988.0    2018.0          CHA
54          0  1610610029    1948.0    1948.0          NaN
55          0  1610610025    1946.0    1949.0          NaN
56          0  1610610034    1946.0    1949.0          NaN
57          0  1610610036    1946.0    1950.0          NaN
58          0  1610610024    1947.0    1954.0          NaN
59          0  1610610031    1946.0    1946.0          NaN
60          0  1610610027    1949.0    1949.0          NaN
61          0  1610610030    1949.0    1952.0          NaN
62          0  1610610033    1949.0    1949.0          NaN
63          0  1610610037    1949.0    1949.0          NaN
64          0  1610610023    1949.0    1949.0          NaN
65          0  1610610026    1946.0    1946.0          NaN
66          0  1610610028    1946.0    1946.0          NaN
67          0  1610610032    1946.0    1948.0          NaN
68          0  1610610035    1946.0    1946.0          NaN

In [33]:
df3[df3['team_id'] == 1610612762]

    league_id     team_id  min_year  max_year abbreviation
49          0  1610612762    1974.0    2018.0          UTA

In [34]:
df3[df3['team_id'] == 1610612763]

    league_id     team_id  min_year  max_year abbreviation
50          0  1610612763    1995.0    2018.0          MEM

<font color='red'> second team in matchup appears to be the detailed team for that row in df2 betting spread table
    
    
care to check for more entries?????????<font>